# This is a basic workflow to help you get started with Actions

name: Blog Build

on:
  # Runs on pushes targeting the default branch
  push:
    paths: 
      - 'site/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./site
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true # Checkout private submodules(themes or something else).
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install Dependencies
        run: npm ci
        working-directory: ${{ env.working-directory }}
      - name: Build
        run: npm run build
        working-directory: ${{ env.working-directory }}
      - name: Cache Build Output
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.OS }}-blog-build-cache
          restore-keys: |
            ${{ runner.OS }}-blog-build-cache
